apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox2
  source:
    repoURL: https://charts.netbox.oss.netboxlabs.com/
    chart: netbox
    targetRevision: 7.1.10
    helm:
      releaseName: netbox
      values: |
        global:
          storageClass: truenas-nfs-csi
        
        # --- NetBox コンテナ（プラグインを内包したカスタムイメージを推奨） ---
        image:
          # 例：あなたのレジストリのカスタムイメージ
          registry: ghcr.io
          # repository: netbox-community/netbox
          repository: zinntikumugai/netbox-custom
          tag: "latest"
          pullPolicy: Always
        
        plugins:
          - netbox_diode_plugin
          - netbox_bgp
        pluginsConfig:
          netbox_diode_plugin:
            diode_target_override: "grpc://netbox-diode-ingress-nginx-controller.netbox-diode.svc.cluster.local:80/diode"
            diode_username: "diode"
            netbox_to_diode_client_secret: "0123456789"
          netbox_bgp:
            device_ext_page: "right"
            top_level_menu: false
        
        # --- PostgreSQL subchart設定（PDB重複回避） ---
        postgresql:
          enabled: true
          # 固有ラベルを全リソースに付与
          commonLabels:
            app.z1n.in/stack: netbox
          # 既存Secretからパスワードを読み込む
          auth:
            existingSecret: "netbox-postgresql-auth"
            secretKeys:
              adminPasswordKey: "postgres-password"
              userPasswordKey: "password"
          primary:
            # Podにも固有ラベルを付与
            podLabels:
              app.z1n.in/stack: netbox
              app.z1n.in/component: postgresql
            # Helmチャートのデフォルトサービスを無効化
            service:
              enabled: false
          # PDB設定（セレクタに固有ラベルを追加）
          pdb:
            create: true
            minAvailable: 1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
