apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox-diode
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox-diode
  source:
    repoURL: https://netboxlabs.github.io/diode/charts
    chart: diode
    targetRevision: 1.8.1
    helm:
      releaseName: netbox
      values: |
        # PostgreSQL configuration using existing PVC
        postgresql:
          enabled: true
          # 固有ラベルを全リソースに付与（PDB重複回避）
          commonLabels:
            app.z1n.in/stack: diode
          auth:
            existingSecret: "diode-postgresql-secret"
            secretKeys:
              adminPasswordKey: "postgres-password"
          primary:
            # Podにも固有ラベルを付与
            podLabels:
              app.z1n.in/stack: diode
              app.z1n.in/component: postgresql
            persistence:
              enabled: true
              existingClaim: "data-netbox-postgresql-0"
            # Helmチャートのデフォルトサービスを無効化
            service:
              enabled: false
          # PDB設定（セレクタに固有ラベルを追加）
          pdb:
            create: true
            minAvailable: 1
        
        # Redis configuration using existing PVC
        redis:
          enabled: true
          # 固有ラベルを全リソースに付与
          commonLabels:
            app.z1n.in/stack: diode
          auth:
            existingSecret: "diode-redis-secret"
            existingSecretPasswordKey: "redis-password"
          master:
            # Podにも固有ラベルを付与
            podLabels:
              app.z1n.in/stack: diode
              app.z1n.in/component: redis-master
            persistence:
              enabled: true
              existingClaim: "redis-data-netbox-redis-master-0"
            # Helmチャートのデフォルトサービスを無効化
            service:
              enabled: false
          replica:
            # Podにも固有ラベルを付与
            podLabels:
              app.z1n.in/stack: diode
              app.z1n.in/component: redis-replica
            persistence:
              enabled: true
              existingClaim: "redis-data-netbox-redis-replica-0"
            # Helmチャートのデフォルトサービスを無効化
            service:
              enabled: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true