# Netbox Diode Secrets with fixed password: 0123456789
apiVersion: v1
kind: Secret
metadata:
  name: diode-postgresql-secret
  namespace: netbox-diode
type: Opaque
data:
  postgres-database: cG9zdGdyZXM=      # base64: postgres
  postgres-username: cG9zdGdyZXM=      # base64: postgres
  postgres-password: MDEyMzQ1Njc4OQ==  # base64: 0123456789
  diode-database: ZGlvZGU=             # base64: diode
  diode-username: ZGlvZGU=             # base64: diode
  diode-password: MDEyMzQ1Njc4OQ==     # base64: 0123456789
  hydra-database: aHlkcmE=             # base64: hydra
  hydra-username: aHlkcmE=             # base64: hydra
  hydra-password: MDEyMzQ1Njc4OQ==     # base64: 0123456789

---
apiVersion: v1
kind: Secret
metadata:
  name: diode-redis-secret
  namespace: netbox-diode
type: Opaque
data:
  redis-password: MDEyMzQ1Njc4OQ==     # base64: 0123456789

---
apiVersion: v1
kind: Secret
metadata:
  name: diode-hydra-secret
  namespace: netbox-diode
type: Opaque
data:
  secretsCookie: MDEyMzQ1Njc4OQ==      # base64: 0123456789
  secretsSystem: MDEyMzQ1Njc4OQ==      # base64: 0123456789
  dsn: cG9zdGdyZXM6Ly9oeWRyYTowMTIzNDU2Nzg5QG5ldGJveC1kaW9kZS1wb3N0Z3Jlc3FsLm5ldGJveC1kaW9kZS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2h5ZHJhP3NzbG1vZGU9ZGlzYWJsZQ==  # base64: postgres://hydra:0123456789@netbox-diode-postgresql.netbox-diode.svc.cluster.local:5432/hydra?sslmode=disable

---
apiVersion: v1
kind: Secret
metadata:
  name: diode-auth-oauth2-secret
  namespace: netbox-diode
type: Opaque
data:
  client-credentials.json: W3siY2xpZW50X2lkIjoiZGlvZGUtaW5nZXN0IiwiY2xpZW50X3NlY3JldCI6IjAxMjM0NTY3ODkiLCJncmFudF90eXBlcyI6WyJjbGllbnRfY3JlZGVudGlhbHMiXSwic2NvcGUiOiJkaW9kZTppbmdlc3QifSx7ImNsaWVudF9pZCI6ImRpb2RlLXRvLW5ldGJveCIsImNsaWVudF9zZWNyZXQiOiIwMTIzNDU2Nzg5IiwiZ3JhbnRfdHlwZXMiOlsiY2xpZW50X2NyZWRlbnRpYWxzIl0sInNjb3BlIjoibmV0Ym94OnJlYWQgbmV0Ym94OndyaXRlIn0seyJjbGllbnRfaWQiOiJuZXRib3gtdG8tZGlvZGUiLCJjbGllbnRfc2VjcmV0IjoiMDEyMzQ1Njc4OSIsImdyYW50X3R5cGVzIjpbImNsaWVudF9jcmVkZW50aWFscyJdLCJzY29wZSI6ImRpb2RlOnJlYWQgZGlvZGU6d3JpdGUifV0=  # base64: OAuth2 client credentials JSON

---
apiVersion: v1
kind: Secret
metadata:
  name: diode-ingester-secret
  namespace: netbox-diode
type: Opaque
data:
  REDIS_PASSWORD: MDEyMzQ1Njc4OQ==     # base64: 0123456789

---
apiVersion: v1
kind: Secret
metadata:
  name: diode-reconciler-secret
  namespace: netbox-diode
type: Opaque
data:
  REDIS_PASSWORD: MDEyMzQ1Njc4OQ==     # base64: 0123456789
  POSTGRES_PASSWORD: MDEyMzQ1Njc4OQ==  # base64: 0123456789
  DIODE_TO_NETBOX_CLIENT_SECRET: MDEyMzQ1Njc4OQ==  # base64: 0123456789