# Pre-created PVCs for netbox-diode to ensure truenas-nfs-csi storage class usage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-netbox-postgresql-0
  namespace: netbox-diode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-netbox-redis-master-0
  namespace: netbox-diode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-netbox-redis-replica-0
  namespace: netbox-diode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-csi
  resources:
    requests:
      storage: 1Gi