apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox-diode
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox2
  source:
    repoURL: https://netboxlabs.github.io/diode/charts
    chart: diode
    targetRevision: 1.8.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
