apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orb-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox-orb
  source:
    repoURL: https://github.com/zinntikumugai/netbox-additional-plugin-apps.git
    path: charts/orb
    targetRevision: main
    helm:
      releaseName: orb-agent
      values: |
        # --- Global Configuration ---
        global:
          storageClass: truenas-nfs-csi

        # --- Image Configuration ---
        image:
          repository: netboxlabs/orb-agent
          tag: latest
          pullPolicy: Always

        # --- Diode Backend Configuration ---
        diode:
          # Diodeエンドポイント（Ingress-Nginx経由でgRPC接続）
          target: "grpc://netbox-diode-ingress-nginx-controller.netbox-diode.svc.cluster.local:80/diode"

        # --- Agent Configuration ---
        agent:
          name: "k8s-orb-agent"
          backends:
            networkDiscovery:
              logLevel: "INFO"
            snmpDiscovery: {}
          policies:
            networkDiscovery:
              enabled: true
              # 10分ごとにネットワークディスカバリーを実行
              schedule: "*/10 * * * *"
              timeout: 10
              defaults:
                # description: "IP discovered by network discovery"
                tags: ["net-discovery", "orb-agent", "k8s"]
              scope:
                fastMode: true
                timing: 4
                icmpEcho: true
              targets:
                # スキャン対象のネットワークCIDR
                - "172.16.1.0/24"
                - "172.16.11.0/24"
                - "172.16.101.0/24"
                - "172.16.120.0/24"
                - "172.16.150.0/24"
                - "192.168.10.0/24"
            snmpDiscovery:
              enabled: true
              # SNMP Walk設定
              schedule: "*/10 * * * *"
              timeout: 120
              defaults:
                tags: ["snmp-discovery", "orb-agent", "k8s"]
                # エンティティごとのデフォルト設定
                device:
                  description: "SNMP discovered device"
                  comments: "Automatically discovered via Orb Agent"
                interface:
                  description: "SNMP discovered interface"
                  if_type: "other"  # NetBox required field
                ip_address:
                  description: "SNMP discovered IP address"
                  role: "management"
              targets:
                - host: "192.168.10.10"
                - host: "172.16.1.254"
              authentication:
                protocolVersion: "SNMPv2c"
                community: "public"

        # --- Credentials Configuration ---
        credentials:
          # Secretを別途手動管理するため false に設定
          # argocd/applications/orb-agent-secrets.yaml を手動適用してください
          create: false
          secretName: "orb-diode-credentials"

        # --- Security Context Configuration ---
        security:
          runAsUser: 0
          capabilities:
            - NET_RAW
            - NET_ADMIN
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault

        # --- Service Account Configuration ---
        serviceAccount:
          create: true
          annotations: {}

        # --- RBAC Configuration ---
        rbac:
          create: true

        # --- DaemonSet Configuration ---
        daemonset:
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1

        # --- Resource Limits ---
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # --- Node Selection ---
        # nodeSelector:
        #   node-role.kubernetes.io/worker: "true"
        # tolerations: []
        # affinity: {}

        # --- Network Policy ---
        networkPolicy:
          enabled: false  # 必要に応じて有効化
          egress:
            allowDNS: true
            diodeEndpoint:
              # 自動的にdiode.targetから抽出されますが、明示的に指定も可能
              # host: "netbox-diode-ingress-nginx-controller.netbox-diode.svc.cluster.local"
              # port: 80

        # --- Pod Disruption Budget ---
        pdb:
          enabled: false  # 本番環境では有効化を推奨
          minAvailable: 1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
